### ISSUE TITLE
IJava issue with format strings in System.out.printf()

### ISSUE THREAD

**Issue by Poonna** [SpencerPark/IJava#13]
Hello,

I've been looking for a Java kernel for Jupyter Notebook, and I'm really glad to have finally found your excellent IJava kernel. I've been testing it for a while now and all seems to be working great, except for one thing. I found a problem when using IJava kernel with the following example code using System.out.printf().

```java
public class Employee {
    private String name;
    private double salary;
    
    public Employee(String name, double salary) {
        this.name = name;
        this.salary = salary;
    }

    public void showProfile() {
        System.out.printf("Name: %s%n", name);
        System.out.printf("Salary: %.2f%n", salary);
    }
}
```

This is the output when trying to execute the code:

```
|           System.out.printf("Name: __MAGICS.applyLineMagic(new String(Base64.getDecoder().decode("cyVuLCBuYW1lKTs=")),List.of());
')' expected

|           System.out.printf("Name: __MAGICS.applyLineMagic(new String(Base64.getDecoder().decode("cyVuLCBuYW1lKTs=")),List.of());
unclosed string literal

|           System.out.printf("Salary: %.2f__MAGICS.applyLineMagic(new String(Base64.getDecoder().decode("biwgc2FsYXJ5KTs=")),List.of());
')' expected

|           System.out.printf("Salary: %.2f__MAGICS.applyLineMagic(new String(Base64.getDecoder().decode("biwgc2FsYXJ5KTs=")),List.of());
unclosed string literal
```

From further inspection, I think it probably has something to do with parsing those "%s" and "%f" in the strings. It doesn't have to be with System.out.printf(). It actually happens anywhere where a string contains those format specifiers. A percent mark ("%") alone, though, will not produce the errors. It has to be a format specifier.

Please let me know if I could be of any further assistance.

Thanks,
Poonna

**Comment by SpencerPark** [comment]
Hi Poonna,

> I've been looking for a Java kernel for Jupyter Notebook, and I'm really glad to have finally found your excellent IJava kernel.

Thank you, the kind words are very motivating!

> I think it probably has something to do with parsing those "%s" and "%f" in the strings.

You are absolutely right, this is something that was overlooked. The parsing is for the magic system (like ipython's line and cell magics) in what I thought was a language neutral way but forgot about string literals. 

The preprocessor will need to do some smarter filtering before doing the magic transformation but until I have time to do that we can just disable the magics. There has been no mention of magic support so hopefully this doesn't break any notebooks but `printf` is something that should indeed take priority.

I'll open up a related issue on the base kernel as well since this is where most of the implementation will happen.

Thanks!
Spencer

**Comment by Poonna** [comment]
Hi Spencer,

Thank you very much. printf() works great now!

There's one more issue related to standard input. I'll open another topic for it. :)

Thanks again!
Poonna
