### ISSUE TITLE
%%loadFromPOM doesn't work for tika-parsers-standard-package after the kernel restart

### ISSUE THREAD

**Issue by sogawa-sps** [SpencerPark/IJava#158]
For some reason, the following instruction doesn't work in a very peculiar way. 

```
%%loadFromPOM
<dependency>
    <groupId>org.apache.tika</groupId>
    <artifactId>tika-parsers-standard-package</artifactId>
    <version>2.9.2</version>
</dependency>

import org.apache.tika.parser.pdf.PDFParser;
```

When you use it the very first time it does work, however, if you restart the kernel it stops working for good. The Jupyter Lab restart doesn't help.  I tried to clean up files like ijava-maven-11439784286752912141.pom but it didn't help either.

![2024-04-11 22_43_42-Untitled ipynb - JupyterLab](https://github.com/SpencerPark/IJava/assets/36852014/41a9fabd-301d-4bf5-b959-d916fb6c814f)

If you change the version to, say, 2.9.1 the cycle repeats. It works the first time until the kernel restarts.

Reproduces for tika-parsers-standard-package only.

Can be reproduced online.

**Comment by andrus** [comment]
Hi @sogawa-sps , this is already fixed in the **JJava** kernel, which is a supported version of iJava at https://github.com/dflib/jjava . So you can replace iJava with JJava in Jupyter (it is a drop-in replacement), and try again.

Some more info:

* What is JJava: https://github.com/SpencerPark/IJava/issues/161 
* The fix that addresses your issue: https://github.com/dflib/jjava/issues/2

**Comment by sogawa-sps** [comment]
Hi @andrus,

Thank you so much. I confirm that the issue was resolved.
