### ISSUE TITLE
%classpath for relative path?

### ISSUE THREAD

**Issue by truher** [SpencerPark/IJava#164]
hi, i'm puzzled about %classpath.

are relative paths supposed to work?

my file layout:

```
notebook.ipynb
src/main/java/foo/Myclass.java
```

my notebook:

```
%classpath src/main/java

import foo.Myclass;

Myclass class = new Myclass();
```

it can't find the symbol.  All the examples i can find of %classpath seem to involve absolute paths.  do relative paths work?

**Comment by andrus** [comment]
While I don't use `%classpath` (usually relying on `%maven` only), `%classpath` seems to support both absolute and relative paths. Though in your case you are pointing it to the source code directory instead of a directory with compiled `.class` files. So this probably explains the observed behavior. Instead, you may need something like `%classpath target/classes` (or some other folder where `.class` files are placed)

**Comment by truher** [comment]
ahhhh ha ha, yes, thank you, i'm an idiot.  pointing at build/classes/java/main works fine.

the next problem is that those classes are built by gradle in vscode. is the canonical thing to duplicate the gradle dependencies in the maven magic?

**Comment by andrus** [comment]
I think the most canonical way would be to install your local classes to the local Maven repo. I think the command is `gradle publishToMavenLocal` (??) Then you can use a single `%maven` magic pointing to your own artifact, and all the transitive dependencies will be downloaded automatically.

**Comment by truher** [comment]
ok, thanks.
