### ISSUE TITLE
Keyboard input issue with iJava in MacOS 10.13.6

### ISSUE THREAD

**Issue by sesh1989** [SpencerPark/IJava#21]
I have written the following java program:
```
ArrayList <String> sArr = new ArrayList<>();
Scanner keybd = new Scanner(System.in);
for (int i = 0; ; i++)
{
    System.out.println("Type a number. Terminate by giving -99");
    String input = keybd.nextLine();
    if (input.contains("-99"))
        break;
    sArr.add(input);
}

for (String s1 : sArr)
    System.out.println(s1);
```
The first **for** loop should exit on receiving **-99** from keyboard and the second **for** loop should print the numbers read. But, the first for loop continues to get standard input ad infinitum even after -99 is entered. A similar issue https://github.com/SpencerPark/IJava/issues/14 is reported to be closed, but the bug seems to be rearing its ugly head still.

**Comment by SpencerPark** [comment]
Just a quick explanation on what was happening, the input stream was using a default implementation for the bulk read which would try and read the entire requested length which when using a buffered reader or scanner would keep triggering a request for more data until the internal buffer was filled.

The new implementation is non-blocking and only reads a line at a time so that it lazily makes requests for more input. I've tested your example and everything appears to be working now but please reopen if you find the problem persists.

Thanks for the bug report!
