### ISSUE TITLE
first kernel instruction gives illegal character in notebook

### ISSUE THREAD

**Issue by nherbaut** [SpencerPark/IJava#23]
Hello,

I'm trying to setup a java101 class using your kernel. It seems to kinda work, except that I have the following issue:

Upon restarting the kernel,  the execution of the first instruction always return an illegal character error with some binary garbage. The second execution, however works as expected, see the attached screenshot
![image](https://user-images.githubusercontent.com/960823/44333666-cc41f580-a46f-11e8-8822-59a2a4e2f7a8.png)

I can't reproduce the issue with a "jupyterlab console" or with a "terminal jupyter console", just with notebooks.

Installation info:

cbc186831b36ed557e7bc48b1cfcdc1e  ijava-1.1.1.jar
4.4.0 jupyter --version
0.9.2 jupyterhub --version
10.0.2 javac -version
10.0.2 java -version 
16.04 Ubuntu

System is installed with the following ansible playbook: https://github.com/nherbaut/jupyterhub-deploy-teaching

Thanks!

**Comment by nherbaut** [comment]
I can grant access to a server that shows the pb if needed

**Comment by SpencerPark** [comment]
>   I'm trying to setup a java101 class using your kernel.

That's fantastic! I appreciate the risk you are taking using an open source projects for a class and I'll try to get any issues fixed quickly.

>   I can grant access to a server that shows the pb if needed

@nherbaut, thanks that would be very helpful. This seems very dependent on the setup and I feel I would have trouble reproducing otherwise.

**Comment by nherbaut** [comment]
@SpencerPark you can log in the [server](https://teaching.nextnet.top) through github oauth. Should you need a shell, please post your public ssh key.

**Comment by SpencerPark** [comment]
Access to the server was very helpful. A blank `IJAVA_STARTUP_SCRIPTS_PATH` variable (rather than an unset one) was adding everything in the root directory to the startup scripts which resulted in adding some random binary files. These were trying to be read as java source which resulted in the gibberish in the error messages.

The startup scripts are only executed once (and immediately before) the first cell evaluation so that any errors make their way to the user which is why it only shows up one time. Anyways should be fixed now :)

**Comment by tobloef** [comment]
I had this error as well, when installing the latest release. I solved it thanks to @SpencerPark comment about the empty options, rather than it being unset. Maybe the default config should be changed?

**Comment by SpencerPark** [comment]
@tobloef there is a fix in 110400f687cd0ca7d8024a1fe929a33241310899 that didn't make it to release yet but should be there soon. I am going to change the configuration as well though, because I think the defaults end up overriding any environment variables used to configure instead which is not the intention.

**Comment by SpencerPark** [comment]
The newest release `1.1.2` fixes these.

**Comment by nherbaut** [comment]
confirmed fixed by 1.1.2, thanks!
