### ISSUE TITLE
Cannot import JUnit

### ISSUE THREAD

**Issue by SeuperHakkerJa** [SpencerPark/IJava#48]
when I try to import JUnit
`import static org.junit.Assert.assertEquals;`
The notebook reports package org.junit does not exist.

I think this might have something to do with the dependencies in the pom.xml?

**Comment by SpencerPark** [comment]
I am assuming you found a fix as the issue is closed but incase others come across this issue I'll leave a possible solution here.

Adding `%maven junit:junit:4.12` to the cell before the import should download (if necessary) and add that dependency to the classpath so that the import would succeed.
