### ISSUE TITLE
Issue with open scanner field

### ISSUE THREAD

**Issue by KSneijders** [SpencerPark/IJava#51]
When executing this code, then not entering anything in the input field and re-executing the code stops the entire project from working. Restarting the kernel fixes the issue.
```
System.out.println("Enter a string: ");
Scanner scan = new Scanner(System.in);
String s1 = scan.nextLine();
```

**Comment by SpencerPark** [comment]
Hi @KSneijders, thanks for raising the issue. This behavior is as expected. The scanner is blocking the execution thread waiting for input which upon reevaluating the cell, clears the input field which prevents the input from ever coming.

IPython behaves the same in this scenario
```python
input()
```

This issue is likely more appropriate upstream in jupyter notebook as it is specifically related to that interface. There is nothing the kernel can do in this scenario other than timeout if you set up that option when installing the kernel (a field in the kernel.json).

I am also curious to see if you can interrupt the kernel in this scenario (the square button in jupyter notebook) which should break it out of that first evaluation.

**Comment by KSneijders** [comment]
Hi @SpencerPark, I tried the interrupt button. The following happened (After starting twice):
First time felt like it did nothing (Closed the second one, which didn't do anything).
Second time gave me an error (intended probably):
```
|   System.out.println(compareStrings());
Evaluation interrupted.
```
Then, when starting again, it does show `System.out.println(...);` but the input field does not appear anymore. (Only after kernel restart)

**Comment by SpencerPark** [comment]
Thanks for the update @KSneijders, a second interrupt gave control back so code can be evaluated again but the stdin stream seems permanently blocked. This is in fact a bug we should be fixing as the IPython kernel only takes a single interrupt and is then free to use stdin again.

**Comment by SpencerPark** [comment]
Hey @KSneijders, I know it's been a while, but are you still experiencing this? Running the cell a 2nd time of course causes that issue with deleting the input box but interrupting it seems to be working fine. I get a fresh input box and everything runs as expected.

Not sure of any Jupyter updates but maybe this was the result of a different bug?

**Comment by KSneijders** [comment]
I'm still experiencing the same issue. Do I need to update anything? It's been some time since I used this particular software. Just in case what I'm doing: 
```
System.out.println("Enter a string: ");
Scanner scan = new Scanner(System.in);
String s1 = scan.nextLine();
```
Using the same code:
1. Execute once: Get the input field.
2. Execute twice: No text nor input field.
3. Interrupt Once: The string: "Enter a string: " appears but no input.
4. Interrupt Twice: The same error occurs: 

```
|   String s1 = scan.nextLine();
Evaluation interrupted.
```

**Comment by SpencerPark** [comment]
I would really appreciate it if you could give it a try with the latest IJava release `1.3.0`.

I expect that 1 and 2 should be the same but 3 should give the text box. At least this is what I get with the latest kernel release on Jupyter 5.7.6 but as I don't know what changed I'm worried it is a strange interaction with Jupyter that happened to work out on this version?

Thanks!
