### ISSUE TITLE
Shift Tab documentation

### ISSUE THREAD

**Issue by pdeitel** [SpencerPark/IJava#58]
Is it possible to have the Shift Tab docs display the rendered HTML from the Javadocs? 

It would make the documentation nicer looking and more useful (users could click to follow links, for example). 

Just a suggestion.

Thanks,
Paul

**Comment by SpencerPark** [comment]
Hi Paul, I agree that better javadoc support is important and fairly high on the list of priorities if I get the time. It is a bit tricky though as from my understanding the API doesn't expose much in the way of making readable docs. We can get the raw javadoc but not from snippets and not from external dependencies, only classes in the jdk and only if installed with sources included. The jshell tool does it's own post processing that is not exposed in the API so we need our own as well.

This issue is tracked in #8 so I'll close this and we can move the conversation over there if there is more to add. I'm certainly open to suggestions if there are any libraries or other projects you know of that can extract javadocs from jars/sources and we can either put together our own simple doc formatter or try and somehow use the one from the jdk.

**Comment by pdeitel** [comment]
Thanks!
