### ISSUE TITLE
Module support?

### ISSUE THREAD

**Issue by pdeitel** [SpencerPark/IJava#59]
Any support for adding items to the module path?

**Comment by SpencerPark** [comment]
I'm not too familiar with modules yet. Could you possibly provide an example of how/why this would be used? 

You can certainly provide a module path in the installed `kernel.json` but currently there is no way to modify it at runtime. The jshell API exposes an option for modifying the classpath but the module path requires modifying the compiler options and I believe recompiling all the snippets (or at least declaration ones).

**Comment by pdeitel** [comment]
I am thinking about how I could use this kernel with our Java textbook. In particular, how we'd incorporate libraries that are modularized. In the JShell command line tool, we can use /env to add to the classpath and module path. Ideally, we don't want students to have to modify kernel.json--especially if they're running in an environment where they might not even have access to the folder containing that file.

Can I add a library JAR to the classpath dynamically using this kernel?

I could see this being a great way to learn about and experiment with libraries.

**Comment by SpencerPark** [comment]
That sounds great! I too prefer the notebooks to be as self contained as possible which includes dependencies being declared in the notebooks rather than requiring a certain system setup.

The equivalent to the `/env` command in IJava is a [collection of magics](https://github.com/SpencerPark/IJava/blob/master/docs/magics.md) that you can use at runtime. The magic concept coming from IPython. Specifically:

*   `%classpath` for adding entries to the classpath directly. Intended for use when you have a local package that is compiled but still in the exploded folder layout.
*   `%jars` for adding files to the classpath. Intended for including local jars. If you pass a directory to this one it will add all files in that directory.
*   `%maven` and `%loadFromPOM` for loading dependencies via ivy using maven coordinates. A very popular choice for libs on maven central or other public repos. The POM variant was designed to make it easy to copy and paste a partial POM that includes a dependency (and possibly repository) tag that many libs like to stick in their README. 

If this doesn't cover all the use cases you would need with respect to adding dependencies I'm happy to hear what extensions would be useful!

**Comment by pdeitel** [comment]
Actually, those probably will cover it all. I apologize if I missed any of that in the docs. And I appreciate your detailed responses!

**Comment by SpencerPark** [comment]
No worries, if you missed it someone else likely did also :) Lets chalk this one up to a `question`, `solved` then and leave it for others to find.
