### ISSUE TITLE
Shortcut for single line comment

### ISSUE THREAD

**Issue by yangzichao** [SpencerPark/IJava#99]
Hi,
I tried to press command + / to comment/uncomment single line. But it was not working.
Is there any shortcut for commenting?
Thanks!

**Comment by SpencerPark** [comment]
Hi @yangzichao, if there is a keyboard shortcut it will be completely handled by the front-end you are using (rather than the kernel). That being said, on windows, `ctrl` + `/` will line comment in jupyter lab and jupyter notebook with the default bindings.

Try clicking `Help` > `Keyboard Shortcuts` in the jupyter notebook front-end and look for `comment`.

**Comment by yangzichao** [comment]
Thank you so much!
